configure_katello_content_view_versions:
##Publish and promote all envs
#  - content_view: cv-os-rhel-8Server
#    organization: "{{ orgs }}"
#    lifecycle_environments: "{{ configure_katello_lifecycle_environment | map(attribute='name') | list }}"
#    state: present

  - content_view: cv-os-rhel-7Server
    organization: "{{ orgs }}"
    lifecycle_environments: "{{ configure_katello_lifecycle_environment | map(attribute='name') | list }}"
    state: present

#  - content_view: cv-os-rhel-6Server
#    organization: "{{ orgs }}"
#    lifecycle_environments: "{{ configure_katello_lifecycle_environment | map(attribute='name') | list }}"
#    state: present
#
#  - content_view: cv-os-rhel-5Server
#    organization: "{{ orgs }}"
#    lifecycle_environments: "{{ configure_katello_lifecycle_environment | map(attribute='name') | list }}"
#    state: present
