configure_katello_content_view_versions:
##Publish and promote from one env to another
  - content_view: cv-os-rhel-8Server
    organization: "{{ orgs }}"
    lifecycle_environments:
      - Library
    state: present
