configure_katello_content_view_versions:
##Publish and promote from one env to another
# INFRA
  - content_view: ccv-infra-sat6-capsule-rh7
    organization: "{{ orgs }}"
    current_lifecycle_environment: InfraTest
    lifecycle_environments:
      - InfraProd
    state: present
