---
- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ dir_orgs_vars }}/configure_foreman_katello_credentials.yml"
    - "{{ dir_orgs_vars }}/configure_foreman_katello_general.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/configure_katello_lifecycle_environments.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/cv/configure_katello_content_views_filter.yml"
  when: orgs is defined and dir_orgs_vars is defined

- name: Create Content View Filters
  #theforeman.foreman.katello_content_view_filter:
  redhat.satellite.content_view_filter:
    username: "{{ configure_foreman_username }}"
    password: "{{ configure_foreman_password }}"
    server_url: "{{ configure_foreman_server_url }}"
    validate_certs: "{{ configure_foreman_validate_certs }}"
    name: "{{ item.name }}"
    content_view: "{{ item.content_view }}"
    filter_type: "{{ item.filter_type }}"
    organization: "{{ item.organization }}"
    date_type: "{{ item.date_type | default(omit) }}"
    end_date: "{{ item.end_date | default(omit) }}"
    errata_id: "{{ item.errata_id | default(omit) }}"
    inclusion: "{{ item.inclusion | default(omit) }}"
    max_version: "{{ item.max_version | default(omit) }}"
    min_version: "{{ item.min_version | default(omit) }}"
    repositories: "{{ item.repositories | default(omit) }}"
    rule_name: "{{ item.rule_name | default(omit) }}"
    start_date: "{{ item.start_date | default(omit) }}"
    types: "{{ item.types | default(omit) }}"
    version: "{{ item. version| default(omit) }}"
    filter_state: "{{ item.filter_state | default(omit) }}"
    rule_state: "{{ item.rule_state | default(omit) }}"
  loop: "{{ configure_katello_content_view_filters }}"
  when: configure_katello_content_view_filters is defined
  delegate_to: "{{ 'localhost' if foreman_local else omit }}"
