---
- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ dir_orgs_vars }}/configure_foreman_katello_credentials.yml"
    - "{{ dir_orgs_vars }}/configure_foreman_katello_general.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/configure_katello_host_collections.yml"
  when: orgs is defined and dir_orgs_vars is defined

- name: Ensure Host Collection is correct
  theforeman.foreman.katello_host_collection:
    username: "{{ configure_foreman_username }}"
    password: "{{ configure_foreman_password }}"
    server_url: "{{ configure_foreman_server_url }}"
    validate_certs: "{{ configure_foreman_validate_certs }}"
    name: "{{ item.name }}"
    organization: "{{ orgs }}"
    description: "{{ item.description  | default(omit) }}"
    updated_name: "{{ item.updated_name  | default(omit) }}"
    state: "{{ item.state  | default(omit) }}"
  loop: "{{ configure_katello_host_collections }}"
  when: configure_katello_host_collections is defined
  delegate_to: "{{ 'localhost' if foreman_local else omit }}"

- name: Add hosts to a host collection
  command: "hammer host-collection add-host --name {{ item.name }} --hosts {% for host in item.hosts%}{{ host }}{% if not loop.last %},{% endif %}{% endfor %} --organization {{ orgs }}"
  become: "yes"
  register: cmd_purge_result
  loop: "{{ configure_katello_host_collections }}"
  failed_when: >
    (cmd_purge_result.rc not in [0, 73])
  changed_when: (cmd_purge_result.rc in [0])
  when: configure_katello_host_collections is defined and item.hosts is defined 
  delegate_to: "{{ satellite_fqdn }}"
