---
- include_vars:
    file: "{{ item }}"
  loop: 
    - "{{ dir_orgs_vars }}/configure_foreman_katello_credentials.yml"
    - "{{ dir_orgs_vars }}/configure_foreman_katello_general.yml"
    - "{{ dir_orgs_vars }}/{{ orgs }}/configure_foreman_organization.yml"
  when: orgs is defined and dir_orgs_vars is defined

- name: Create Organizations
  theforeman.foreman.foreman_organization:
    username: "{{ configure_foreman_username }}"
    password: "{{ configure_foreman_password }}"
    server_url: "{{ configure_foreman_server_url }}"
    validate_certs: "{{ configure_foreman_validate_certs }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ configure_foreman_organizations }}"
  when: configure_foreman_organizations is defined
  delegate_to: "{{ 'localhost' if foreman_local else omit }}"
