---
vault_foreman_admin_username: "admin"
vault_foreman_admin_password: "redhat00"
vault_rhn_user: redhat-support-active-account
vault_rhn_pwd: p4$$W0rD
vault_rhn_pool_ids: 01123581321245589144233377610987
#vault_katello_proxy_url: http://proxy.com
#vault_katello_proxy_port: 9090
#vault_katello_proxy_username: admin
#vault_katello_proxy_password: redhat00
