---
foreman_local: true
configure_katello_username: admin
configure_katello_password: "{{ vault_katello_admin_password | default('redhat00') }}"
configure_katello_server_url: "https://satellite.bcnconsulting.com"
configure_katello_validate_certs: false
configure_katello_install_deps: true
configure_katello_copy_manifest: false
configure_katello_force_manifest: false
