configure_katello_repository_sets:
###########
## RHEL8 
###########
  - name:  Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
    repo_name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux for x86_64
    state: enabled
    repositories:
      - releasever: 8
      - releasever: 8.1

  - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
    repo_name: Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs
    organization: biffco
    product: Red Hat Enterprise Linux for x86_64
    state: enabled
    repositories:
      - releasever: 8
      - releasever: 8.1

  - name: Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)
    repo_name: Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux for x86_64
    state: enabled
    repositories:
      - releasever: 8
      - releasever: 8.1
###########
## RHEL7
###########
  - name: Red Hat Enterprise Linux 7 Server (RPMs)
    repo_name: Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - releasever: 7Server
        basearch: x86_64
      - releasever: 7.7
        basearch: x86_64
      - releasever: 7.6
        basearch: x86_64

  - name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
    repo_name: Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64 
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - basearch: x86_64
        
  - name: Red Hat Enterprise Linux 7 Server - RH Common (RPMs)
    repo_name: Red Hat Enterprise Linux 7 Server - RH Common (RPMs) 
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - releasever: 7Server
        basearch: x86_64
      - releasever: 7.7
        basearch: x86_64
      - releasever: 7.6
        basearch: x86_64

  - name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
    repo_name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - releasever: 7Server
        basearch: x86_64
      - releasever: 7.7
        basearch: x86_64
      - releasever: 7.6
        basearch: x86_64

  - name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
    repo_name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - releasever: 7Server
        basearch: x86_64
      - releasever: 7.7
        basearch: x86_64
      - releasever: 7.6
        basearch: x86_64
############
### RHEL6 
############
  - name: Red Hat Enterprise Linux 6 Server (RPMs)
    repo_name: Red Hat Enterprise Linux 6 Server RPMs x86_64 7Server
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: disabled
    repositories:
      - releasever: 6Server
        basearch: x86_64
      - releasever: 6.10
        basearch: x86_64
      - releasever: 6.9
        basearch: x86_64

  - name: Red Hat Enterprise Linux 6 Server - Extras (RPMs)
    repo_name: Red Hat Enterprise Linux 6 Server - Extras RPMs x86_64 
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: disabled
    repositories:
      - basearch: x86_64
        
  - name: Red Hat Enterprise Linux 6 Server - RH Common (RPMs)
    repo_name: Red Hat Enterprise Linux 6 Server - RH Common (RPMs) 
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: disabled
    repositories:
      - releasever: 6Server
        basearch: x86_64
      - releasever: 6.10
        basearch: x86_64
      - releasever: 6.9
        basearch: x86_64

  - name: Red Hat Enterprise Linux 6 Server - Optional (RPMs)
    repo_name: Red Hat Enterprise Linux 6 Server - Optional (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: disabled
    repositories:
      - releasever: 6Server
        basearch: x86_64
      - releasever: 6.10
        basearch: x86_64
      - releasever: 6.9
        basearch: x86_64

  - name: Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)
    repo_name: Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: disabled
    repositories:
      - releasever: 6Server
        basearch: x86_64
      - releasever: 6.10
        basearch: x86_64
      - releasever: 6.9
        basearch: x86_64

###########
## SAT6.6 
###########
  - name: Red Hat Satellite Tools 6.6 (for RHEL 7 Server) (RPMs)
    repo_name: Red Hat Satellite Tools 6.6 (for RHEL 7 Server) (RPMs)
    organization: biffco
    product: Red Hat Enterprise Linux Server
    state: enabled
    repositories:
      - basearch: x86_64

  - name: Red Hat Satellite Capsule 6.6 (for RHEL 7 Server) (RPMs)
    #repo_name: Red Hat Satellite Capsule 6.6 (for RHEL 7 Server) (RPMs)
    repo_name: Red Hat Satellite Capsule 6.6 for RHEL 7 Server RPMs x86_64
    organization: biffco
    product: Red Hat Satellite Capsule
    state: enabled
    repositories:
      - basearch: x86_64

###########
## OCP
###########
  - name: Red Hat OpenShift Container Platform 3.11 (RPMs)
    repo_name: Red Hat OpenShift Container Platform 3.11 RPMs x86_64 
    organization: biffco
    product: Red Hat OpenShift Container Platform
    state: disabled
    repositories:
      - basearch: x86_64

###########
### Sofware Collections
############
#  - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
#    repo_name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
#    organization: biffco
#    product: Red Hat Software Collections for RHEL Server 
#    state: disabled
#    repositories:
#      - releasever: 7Server
#        basearch: x86_64
#      - releasever: 7.7
#        basearch: x86_64
#      - releasever: 7.6
#        basearch: x86_64
#
###########
## ANSIBLE
###########
  - name: Red Hat Ansible Engine 2.7 RPMs for Red Hat Enterprise Linux 7 Server
    repo_name: Red Hat Ansible Engine 2.7 RPMs for Red Hat Enterprise Linux 7 Server
    organization: biffco
    product: Red Hat Ansible Engine
    state: disabled
    repositories:
      - basearch: x86_64

  - name: Red Hat Ansible Engine 2.8 RPMs for Red Hat Enterprise Linux 7 Server
    repo_name: Red Hat Ansible Engine 2.8 RPMs for Red Hat Enterprise Linux 7 Server
    organization: biffco
    product: Red Hat Ansible Engine 
    state: disabled
    repositories:
      - basearch: x86_64


#  - name: Red Hat Ansible Engine 2.8 for RHEL 8 x86_64 (RPMs)
#    repo_name: Red Hat Ansible Engine 2.8 for RHEL 8 x86_64 (RPMs)
#    organization: biffco
#    product: Red Hat Ansible Engine
#    state: disabled
#    repositories:
#      - basearch: x86_64
#
#  - name: Red Hat Ansible Engine 2.9 for RHEL 8 x86_64 (RPMs)
#    repo_name: Red Hat Ansible Engine 2.9 for RHEL 8 x86_64 RPMs
#    organization: biffco
#    product: Red Hat Ansible Engine
#    state: enabled
#    repositories:
#      - basearch: x86_64

configure_katello_repositories:
  - name: EPEL-7
    organization: biffco
    product: EPEL
    state: present
    content_type: yum
    url: http://dl.fedoraproject.org/pub/epel/7Server/x86_64/
    #gpg_key: 
    gpg_key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    download_policy: on_demand
