configure_katello_content_view_versions:
##Publish and promote from one env to another
#  - content_view: cv-os-rhel-8Server
#    organization: "{{ orgs }}"
#    current_lifecycle_environment: InfraTest 
#    lifecycle_environments:
#      - InfraProd
#    state: present

  - content_view: cv-os-rhel-7Server
    organization: "{{ orgs }}"
    current_lifecycle_environment: InfraTest
    lifecycle_environments:
      - InfraProd
    state: present
