configure_katello_content_view_versions:
##Publish and promote from one env to another
#  - content_view: cv-os-rhel-8Server
#    organization: "{{ orgs }}"
#    current_lifecycle_environment: Library
#    lifecycle_environments:
#      - InfraTest
#    state: present

  - content_view: cv-os-rhel-7Server
    organization: "{{ orgs }}"
    current_lifecycle_environment: Library
    lifecycle_environments:
      - InfraTest
    state: present
