configure_katello_content_view_versions:
##Publish and promote from one env to another
#  - content_view: cv-os-rhel-7Server
#    organization: "{{ orgs }}"
#    current_lifecycle_environment: Integration
#    lifecycle_environments:
#      - Preproduction
#    state: present

  - content_view: cv-os-rhel-7Server
    organization: "{{ orgs }}"
    current_lifecycle_environment: Integration
    lifecycle_environments:
      - Preproduction
    state: present

#  - content_view: cv-os-rhel-6Server
#    organization: "{{ orgs }}"
#    current_lifecycle_environment: Integration
#    lifecycle_environments:
#      - Preproduction
#    state: present
#
#  - content_view: cv-os-rhel-5Server
#    organization: "{{ orgs }}"
#    current_lifecycle_environment: Integration
#    lifecycle_environments:
#      - Preproduction
#    state: present
